# Generated by Django 3.2.18 on 2023-05-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=100, verbose_name='Tarjeta')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('cvc', models.CharField(max_length=3, verbose_name='CVC')),
            ],
        ),
    ]
