# Generated by Django 3.2.18 on 2023-05-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(default='08b0e9', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigoDeBarras',
            field=models.CharField(default='9029e81cb4fe419b859f9d45928eee0f', editable=False, max_length=32, unique=True),
        ),
    ]
