# Generated by Django 3.2.18 on 2023-05-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20230517_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(default='6b90f4', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigoDeBarras',
            field=models.CharField(default='7831aaadb58c410fb68ce4c5cb838b55', editable=False, max_length=32, unique=True),
        ),
    ]
