# Generated by Django 4.1.6 on 2023-05-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='caducidad',
            field=models.DateField(default='2023-12-31'),
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(default='22d288', max_length=6, unique=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='codigoDeBarras',
            field=models.CharField(default='a43461868db84b88a2afc8439f7b368f', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
