# Generated by Django 4.1.6 on 2023-05-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_remove_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carreto',
            fields=[
                ('idCarreto', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombreCarreto', models.CharField(default=None, max_length=50, verbose_name='nombreCarreto')),
                ('productos', models.ManyToManyField(to='catalog.producto')),
            ],
        ),
    ]
