# Generated by Django 3.2.18 on 2023-05-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreto',
            name='id',
            field=models.AutoField(auto_created=True, default='3656fa604b714913bb7ae1e579e8ffa1', primary_key=True, serialize=False),
        ),
    ]
