# Generated by Django 4.1.6 on 2023-05-18 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carreto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carreto',
            name='nombreCarreto',
        ),
        migrations.AddField(
            model_name='carreto',
            name='id',
            field=models.BigAutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carreto',
            name='isBuy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carreto',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
