# Generated by Django 4.1.6 on 2023-05-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreto', '0002_remove_carreto_idcarreto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreto',
            name='id',
            field=models.AutoField(auto_created=True, default='bab5ae82eaf44447b9d09ecb49aa74bf', primary_key=True, serialize=False),
        ),
    ]
