# Generated by Django 4.1.6 on 2023-05-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreto', '0003_alter_carreto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
