# Generated by Django 4.1.6 on 2023-05-18 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carreto', '0004_alter_carreto_id'),
    ]

    operations = [
    ]
